package gpse.example.domain;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.BasicFileAttributes;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

//TODO alle Kommentare und Tests Überarbeiten
//TODO evtl Packages erstellen?
/**
 * The model for the document responsible for initialising the necessary details about the document file.
 */
public class Document {

    private static final String SIGNING_ALGORITHM = "SHA256withRSA";
    /**
     * The documentMetaData containing the identifier as well as other information.
     * The path leading to the document.
     */
    private DocumentMetaData documentMetaData;
    private List<Signatory> Signatories = new ArrayList<>();
    private Map<String, byte[]> advancedSignatures = new HashMap<>();
    private File documentFile;
    private String documentType;
    private SignatureType signatureType = SignatureType.NO_SIGNATURE;

    public Document() {
    }

    public Document(final DocumentMetaData documentMetaData) {
        this.documentMetaData = documentMetaData;
    }

    public Document(final DocumentMetaData documentMetaData, final List<Signatory> signatories) {
        this.documentMetaData = documentMetaData;
        this.Signatories = signatories;
    }

    /**
     * The constructor for a document with a given path to a file.
     * Additionally formats some of the metadata. Uses placeholders for
     * metaUserID, upload timestamp and documentID, for later implementation.
     * Also has to be checked for harmful content in the future.
     * This works only if documentTitle has no dot.
     *
     * @param path        The path leading to the file.
     * @param signatories The list of signatories for a document.
     * @throws IOException throws the exception if filepath was invalid.
     */
    public Document(final String path, final List<Signatory> signatories) throws IOException {
        this.Signatories = signatories;
        Path documentPath = Paths.get(path);
        this.documentFile = new File(path);
        final BasicFileAttributes attr = Files.readAttributes(documentPath, BasicFileAttributes.class);
        final String[] filename = documentFile.getName().split("\\.");
        final String title = filename[0];
        this.documentType = filename[1];
        this.documentMetaData = new DocumentMetaData(new Timestamp(1), title, attr.creationTime(),
            attr.lastModifiedTime(), attr.lastAccessTime(), attr.size());
    }

    /**
     * adds a new signatory to the unsignedSignatory list.
     *
     * @param signatory the ID (e-Mail address) of the new signatory
     */
    public void addSignatory(final Signatory signatory) {

    }

    /**
     * the Method to add an advanced signature for a specific user to the document.
     * @param user the user that signs the document
     */
    //TODO
    public void advancedSignature(final User user) {
        /*
        final String mail = user.getEmail();
        if (unsignedSignatories.contains(mail)) {
            //the new signature is generated by the user and saved in a map to keep the relation beetween user and
            //signature
            advancedSignatures.put(mail, user.advancedSign(this.documentMetaData.getIdentifier()));
            addSignedSignatory(mail);
        }

         */
    }

    /**
     * the method used to verify a signature for a specific user, by checking all public keys a user has.
     * @param user the user who relates to the signature that needs to be checked
     * @return true, if one of the public keys matches with the signature.If thet is not the case we return false.
     */
    //TODO
    public boolean verifySignature(final User user) {
        /*
        final String mail = user.getEmail();
        final byte[] signature = advancedSignatures.get(mail);
        boolean valid = false;
        if (advancedSignatures.containsKey(mail)) {
            try {
                final Signature sign = Signature.getInstance(SIGNING_ALGORITHM);
                final byte[] id = this.documentMetaData.getIdentifier().getBytes();
                final PublicKey[] publicKeys = user.getAllPublicKeys();
                for (final PublicKey publicKey : publicKeys) {
                    sign.initVerify(publicKey);
                    sign.update(id);
                    valid |= sign.verify(signature);
                    if (valid) {
                        break;
                    }
                }
            } catch (NoSuchAlgorithmException | InvalidKeyException | SignatureException exception) {
                System.out.println(exception.getMessage());
            }
        }
        return valid;
         */
        return true;
    }


    public DocumentMetaData getDocumentMetaData() {
        return documentMetaData;
    }

    public File getDocumentFile() {
        return documentFile;
    }

    public String getDocumentTitle() {
        return documentMetaData.getMetaDocumentTitle();
    }

    public String getDocumentType() {
        return documentType;
    }

    public SignatureType getSignatureType() {
        return signatureType;
    }

    public void setSignatureType(final SignatureType signatureType) {
        this.signatureType = signatureType;
    }

    public Map<String, byte[]> getAdvancedSignatures() {
        return advancedSignatures;
    }
}

